version: '3.7'

networks:
  fastapi-network:
    driver: bridge

services:

  redis:
    container_name: "${REDIS_CONTAINER_NAME}"
    image: redis:alpine
    hostname: ${REDIS_CONTAINER_NAME}
    env_file:
      - .dev.env
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/data
    tty: true
    restart: unless-stopped
    networks:
      - fastapi-network

volumes:
  redis:
    driver: local
