version: '3'

networks:
  fastapi-network:
    driver: bridge

services:

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:alpine
    hostname: ${PROJECT_NAME}-redis
    env_file:
      - .docker/dev/redis/config.ini
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/data
    tty: true
    restart: unless-stopped
    networks:
      - fastapi-network

volumes:
  redis:
    driver: local
