version: '3'

networks:
  fastapi-network:
    driver: bridge

services:

  postgresql:
    container_name: ${PROJECT_NAME}-postgresql
    hostname: ${PROJECT_NAME}-postgresql
    image: postgres:15
    restart: unless-stopped
#    environment:
#      POSTGRES_HOST: localhost
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: fast-api-base-project-postgres-name
#      POSTGRES_USER: fast-api-base-project-postgres-user
#      POSTGRES_PASSWORD: fast-api-base-project-postgres-password
    env_file:
      - .env
      - .docker/dev/postgresql/config.ini
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - fastapi-network
    tty: true

  redis:
    container_name: ${PROJECT_NAME}-redis
    hostname: ${PROJECT_NAME}-redis
    image: redis:alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/data/redis
    tty: true
    restart: unless-stopped
    networks:
      - fastapi-network

volumes:
  redis:
    driver: local
  postgres-data:
